### ISSUE TITLE
Error: no such file or directory

### ISSUE THREAD

**Issue by Stolz** [Budry/cadvisor-arm#1] opened 2018-01-02 16:00 UTC
Thanks for your docker image for ARM. 

I've tried running it but `budry/cadvisor-arm:latest` won't start. `docker run` shows this error ...

     standard_init_linux.go:195: exec user process caused "no such file or directory"

... And then exists with code 1

Same error happens when I try to run my own image built using `arm32v7/golang`.

BTHW, the instructions to build from hub.docker.com are not updated, they mention `update.sh` which seems to be gone in current branch

**Comment by Budry** [comment] 2018-01-03 07:07
Hi, this sounds as problem with CPU arch. Which version of ARM you have?

**Comment by Budry** [comment] 2018-01-03 07:37
I'm sorry, you have right. The problem is in version 0.28.3. I'm not sure where is problem I try to fix as soon as possible bot for now version 0.27.2 work perfect, you can use it.

**Comment by Stolz** [comment] 2018-01-03 08:46
Thanks @Budry. Yes, 0.27.2 works fine.

I have an Orange Pi+ 2E (ARMv7 Processor rev 5 v7)

**Comment by Budry** [comment] 2018-01-03 08:59
The problem is in missing glibc in arm alpine. I'm trying to install glibc on arm alpine or change core image from alpine to another (debian maybe)

**Comment by RaymondMouthaan** [comment] 2018-03-04 09:38
Same error shows with v0.29.0

**Comment by Budry** [comment] 2018-03-04 20:12
Thanks for feedback, I sorry for delay but I was very busy. I will publish fix tomorrow

**Comment by Budry** [comment] 2018-03-05 11:48
It should be fixed in db6a26862c2168fcda7d37df891e049272749e5b. It isn't ideal but can be used as temporary workaround. So far I have not found an elegant solution to fix the problem with glibc on arm alpine.

_Bonus: Build image for 0.29.0 is on docker hub_

**Closed as completed by Budry** 2018-03-05 11:48 UTC
Labels: bug
